### ISSUE TITLE
Secure cookie by default

### ISSUE THREAD

**Issue by Findus23** [innocraft/plugin-ForceSSL#2]
Once a website is set up to only use HTTPS I think there shouldn't be a reason not to enable secure (tracking) cookies by default.

Is there an easy way this plugin could do it?

**Comment by tsteur** [comment]
Probably could create a tracker.js file that adds something like `_paq.push(...)` (not sure if that would work)

**Comment by Findus23** [comment]
Superceeded by https://github.com/matomo-org/matomo/issues/14904 and https://github.com/matomo-org/matomo/issues/14395
